# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
# For instructions on configuring this workflow, see comments in the original workflow.

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: internship    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './Student-data-table/Student-Backend'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Generate lock file if not present
      run: |
        if [ ! -f package-lock.json ] && [ ! -f npm-shrinkwrap.json ]; then
          echo "No lock file found, generating package-lock.json."
          npm install --package-lock-only
        fi

    - name: Clean cache and install dependencies
      run: |
        npm cache clean --force
        npm install

    - name: npm install, build, and test
      run: |
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
